apiVersion: jenkins.io/v1
kind: App
metadata:
  annotations:
    jenkins.io/chart-description: A Helm chart for installing Tanzu Mission Control
      on a Kubernetes Cluster
    jenkins.io/chart-repository: https://storage.googleapis.com/ninja-charts/
  creationTimestamp: null
  labels:
    jenkins.io/app-name: tmc-install-chart
    jenkins.io/app-version: 0.1.0
  name: tmc-install-chart
spec: {}
