apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: afewellvmware
    provider: github
    repository: test26235
  name: afewellvmware-test26235
spec:
  description: Imported application for afewellvmware/test26235
  httpCloneURL: https://github.com/afewellvmware/test26235.git
  org: afewellvmware
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test26235
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/afewellvmware/test26235.git
