apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: afewellvmware
    provider: github
    repository: test-jenkins-quickstart
  name: afewellvmware-test-jenkins-quickstart
spec:
  description: Imported application for afewellvmware/test-jenkins-quickstart
  httpCloneURL: https://github.com/afewellvmware/test-jenkins-quickstart.git
  org: afewellvmware
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test-jenkins-quickstart
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/afewellvmware/test-jenkins-quickstart.git
