apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: kampfires
    provider: github
    repository: formio
  name: kampfires-formio
spec:
  description: Imported application for kampfires/formio
  httpCloneURL: https://github.com/kampfires/formio.git
  org: kampfires
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: formio
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/kampfires/formio.git
