apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: kampfires
    provider: github
    repository: guide-builder
  name: kampfires-guide-builder
spec:
  description: Imported application for kampfires/guide-builder
  httpCloneURL: https://github.com/kampfires/guide-builder.git
  org: kampfires
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: guide-builder
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/kampfires/guide-builder.git
