apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ModernAppsNinja
    provider: github
    repository: PksInstallEpmc-LAG-PI9606
  name: modernappsninja-pksinstallepmc-lag-pi9606
spec:
  description: Imported application for ModernAppsNinja/PksInstallEpmc-LAG-PI9606
  httpCloneURL: https://github.com/ModernAppsNinja/PksInstallEpmc-LAG-PI9606.git
  org: ModernAppsNinja
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: PksInstallEpmc-LAG-PI9606
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ModernAppsNinja/PksInstallEpmc-LAG-PI9606.git
