apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: modernappsninja-jxbot
    provider: github
    repository: jx-app-formio-lite
  name: modernappsninja-jxbot-jx-app-formio-lite
spec:
  description: Imported application for modernappsninja-jxbot/jx-app-formio-lite
  httpCloneURL: https://github.com/modernappsninja-jxbot/jx-app-formio-lite.git
  org: modernappsninja-jxbot
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-app-formio-lite
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/modernappsninja-jxbot/jx-app-formio-lite.git
